enum Sort {
  LOWEST_PRICES = "LOWEST_PRICES",
  HIGHEST_PRICES = "HIGHEST_PRICES",
  LATEST_UPDATED = "LATEST_UPDATED",
  OLDEST_UPDATED = "OLDEST_UPDATED",
  LATEST_CREATED = "LATEST_CREATED",
  OLDEST_CREATED = "OLDEST_CREATED"
}

export default Sort;